#!/bin/bash

# SPDX-License-Identifier: Apache-2.0

##
# Build libjpeg-turbo and the libjpeg_turbo_fuzzer harness.
#
# Magma environment variables used:
#   $TARGET   - path to this target's configuration directory
#   $OUT      - path where compiled binaries must be placed
#   $CC       - C compiler (set by the fuzzer's instrument.sh)
#   $CXX      - C++ compiler
#   $CFLAGS   - C compiler flags (includes Magma instrumentation flags)
#   $CXXFLAGS - C++ compiler flags
#   $LDFLAGS  - linker flags
#   $LIBS     - additional libraries to link
##

set -e

cd "$TARGET/repo"

# Reset file timestamps to avoid autotools "file is older than distributed files"
# clock-skew errors inside Singularity containers.
find . -exec touch {} +

# Create an isolated build directory to avoid polluting the source tree.
mkdir -p build && cd build

# Configure libjpeg-turbo as a static library.
# SIMD is disabled to avoid NASM version issues in some environments;
# re-enable it (remove -DWITH_SIMD=FALSE) for better performance if NASM >= 2.10
# is available.
cmake .. \
    -DCMAKE_C_COMPILER="$CC" \
    -DCMAKE_CXX_COMPILER="$CXX" \
    -DCMAKE_C_FLAGS="$CFLAGS" \
    -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
    -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" \
    -DENABLE_SHARED=FALSE \
    -DENABLE_STATIC=TRUE \
    -DWITH_SIMD=FALSE \
    -DCMAKE_BUILD_TYPE=Release

# Build only the libraries (skip CLI tools to speed up the build).
make -j"$(nproc)" jpeg-static turbojpeg-static

# -------------------------------------------------------------------------
# Build the fuzzer harness.
#
# libjpeg-turbo ships its own libFuzzer-style harness in fuzz/.
# We compile it against:
#   - the static libjpeg-turbo libraries built above
#   - $OUT/magma.o  (Magma canary runtime, built by magma/build.sh)
#   - $LIBS / $LDFLAGS as provided by the fuzzer's instrument.sh
# -------------------------------------------------------------------------

# Include paths needed by the harness:
#   - repo root for jpeglib.h / turbojpeg.h
#   - build dir for jconfig.h (generated by CMake)
INCLUDES="-I$TARGET/repo -I$TARGET/repo/build"

$CXX $CXXFLAGS $INCLUDES \
    "$TARGET/repo/fuzz/decompress.cc" \
    "$OUT/magma.o" \
    "$TARGET/repo/build/libjpeg.a" \
    "$TARGET/repo/build/libturbojpeg.a" \
    $LDFLAGS $LIBS \
    -o "$OUT/libjpeg_turbo_fuzzer"
