#!/bin/bash
set -e

##
# Pre-requirements:
# - env TARGET: path to target work dir
# - env OUT: path to directory where artifacts are stored
# - env CC, CXX, FLAGS, LIBS, etc...
##

if [ ! -d "$TARGET/repo" ]; then
    echo "fetch.sh must be executed first."
    exit 1
fi

cd "$TARGET/repo"

# Fix clock skew on BeeGFS / bind-mounted filesystems: touch all files to
# the current time so autotools' sanity checks pass.
find . -exec touch -c {} +

# Run autoreconf separately (NOCONFIGURE=1 prevents autogen.sh from calling
# configure), then touch again to fix any timestamps generated by autoreconf,
# and finally run configure.
NOCONFIGURE=1 ./autogen.sh
find . -exec touch -c {} +

./configure \
	--with-http=no \
	--with-python=no \
	--with-lzma=yes \
	--with-threads=no \
	--disable-shared
make -j"${MAGMA_JOBS:-1}" clean
make -j"${MAGMA_JOBS:-1}" all

TARGET_DIR="$OUT/targets"
mkdir -p "$TARGET_DIR"

cp xmllint "$TARGET_DIR/"

for fuzzer in libxml2_xml_read_memory_fuzzer libxml2_xml_reader_for_file_fuzzer; do
  $CXX $CXXFLAGS -std=c++11 -Iinclude/ -I"$TARGET/src/" \
      "$TARGET/src/$fuzzer.cc" -o "$TARGET_DIR/$fuzzer" \
      .libs/libxml2.a $LDFLAGS $LIBS -lz -llzma
done
